name: "Build ISO"

on:
  push:
    tags:
      - "v*"
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag_name || github.ref }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ISO
        run: nix build .#iso

      - name: Find ISO file
        id: find_iso
        run: echo "iso_path=$(find result/iso -name '*.iso' | head -n 1)" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_name || github.ref_name }}
          name: "Release ${{ inputs.tag_name || github.ref_name }}"
          files: ${{ steps.find_iso.outputs.iso_path }}
